[credentials]

username=
password=
tenant=
server=eu.preservica.com


# The location of the source ZIP files:  Path
storage_root=

# The preservica collection to ingest new content into: UUID
collection_id=

# The cloud bucket connected to the ingest workflow: 
bucket=

# The number of concurrent uploads: Integer
pool_size=

# The location where the Preservica SIPs are written out to before upload
export_folder=

# The ingest workflow name
workflow_name=
